src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CustomerRepository::class)
 */
class Customer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $email;

    /**
     * @ORM\Column(type="decimal", precision=4, scale=1)
     */
    private $weight;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $number_beer;

    /**
     * @ORM\OneToMany(targetEntity=Statistic::class, mappedBy="customer")
     */
    private $statistics;

    /**
     * @ORM\Column(type="integer")
     */
    private $age;

    public function __construct()
    {
        $this->statistics = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getWeight(): ?string
    {
        return $this->weight;
    }

    public function setWeight(string $weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getNumberBeer(): ?int
    {
        return $this->number_beer;
    }

    public function setNumberBeer(int $number_beer): self
    {
        $this->number_beer = $number_beer;

        return $this;
    }

    /**
     * @return Collection|Statistic[]
     */
    public function getStatistics(): Collection
    {
        return $this->statistics;
    }

    public function addStatistic(Statistic $statistic): self
    {
        if (!$this->statistics->contains($statistic)) {
            $this->statistics[] = $statistic;
            $statistic->setCustomer($this);
        }

        return $this;
    }

    public function removeStatistic(Statistic $statistic): self
    {
        if ($this->statistics->removeElement($statistic)) {
            // set the owning side to null (unless already changed)
            if ($statistic->getCustomer() === $this) {
                $statistic->setCustomer(null);
            }
        }

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }
}

src/Controller/BarController.php
<?php

namespace App\Controller;

use App\Entity\Beer;
use App\Repository\BeerRepository;
use App\Repository\CategoryRepository;
use App\Repository\CustomerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\HttpClient\HttpClientInterface;

class BarController extends AbstractController
{
    public function __construct(HttpClientInterface $client, BeerRepository $beerRepo, CategoryRepository $categoryRepo, CustomerRepository $customerRepo)
    {
        $this->client = $client;
        $this->beerRepo = $beerRepo;
        $this->categoryRepo = $categoryRepo;
        $this->customerRepo = $customerRepo;
    }

    /**
     * @Route("/", name="home")
     */
    public function index(): Response
    {
        $beers = $this->beerRepo->findById();

        return $this->render('bar/index.html.twig', compact('beers'));
    }

    /**
    * @Route("/menu", name="menu")
    */
    public function mainMenu(string $category_id, string $routeName): Response{
        $categories = $this->categoryRepo->findByTerm('normal');

        return $this->render('partials/main_menu.html.twig', ['category_id' => $category_id, 'routeName' => $routeName, 'categories' => $categories ]);
    }

    /**
     * @Route("/beer/{id}", name="showBeer")
     */
    public function showBeer($id): Response
    {
        $beer = $this->beerRepo->find($id);

        return $this->render('beers/show.html.twig', compact('beer'));
    }

    /**
     * @Route("/mention", name="mention")
     */
    public function mention()
    {
        $title = 'Mentions légales';

        return $this->render('bar/mention.html.twig', compact('title'));
    }

    /**
     * @Route("/beers", name="beers")
     */
    public function beers()
    {
        $beers = $this->beers_api()['beers'];

        $title = 'Page des bières';

        return $this->render('beers/index.html.twig', compact('beers', 'title'));
    }

    private function beers_api(): array
    {
        $response = $this->client->request(
            'GET',
            'https://raw.githubusercontent.com/Antoine07/hetic_symfony/main/Introduction/Data/beers.json'
        );

        $statusCode = $response->getStatusCode();
        // $statusCode = 200
        $contentType = $response->getHeaders()['content-type'][0];
        // $contentType = 'application/json'
        $content = $response->getContent();
        // $content = '{"id":521583, "name":"symfony-docs", ...}'
        $content = $response->toArray();
        // $content = ['id' => 521583, 'name' => 'symfony-docs', ...]

        return $content ;
    }

    /**
     * @Route("/category/{id}", name="showCategory")
     */
    public function showCategory($id)
    {
        $category = $this->categoryRepo->find($id);

        $title = "Détail catégorie";

        return $this->render('categories/show.html.twig', compact('category', 'title'));
    }

    /**
     * @Route("/statistics", name="statistics")
     */
    public function statitstics()
    {
        $customers = $this->customerRepo->findAll();

        return $this->render('bar/statistics.html.twig', compact('customers'));
    }

    /**
     * @Route("/partie-4", name="partie-4")
     */
    public function partie4()
    {
        // La methode attend en paramètre l'id d'une bière et non pas l'id d'une catégorie 
        // Selon nous il aurait donc été préferable de mettre cette méthode dans le BeerRepository et non pas dans le CategoryRepository
        // La methode permet de nous donner la catégorie de la bière passée en parametre seulement si la bière appartient une catégorie 
        // dont le est a la champ term = "special"
 
        dd($this->categoryRepo->findCatSpecial(/* Beer ID */));
    }
}

templates/bar/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BarController!{% endblock %}

{% block body %}
<div class="row">
  <div class="col-sm-6">
  {% for beer in beers %}
    <div class="card">
      <div class="card-body">
        <a href="{{ path('showBeer', { 'id' : beer.id }) }}"><h5 class="card-title">{{ beer.name }}</h5></a>
        <p class="card-text">{{ beer.description }}</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  {% endfor %}
  </div>
</div>
{% endblock %}

templates/bar/mention.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ title }}</h5>
        <p class="card-text">
          La page des mentions légales
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/bar/statistics.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BarController!{% endblock %}

{% block body %}

    <p>Nombre de clients : {{ customers|length }}</p>

    {% for customer in customers %}
    <div class="card">
        <div>
            <p class="card-text"> Pseudo : <strong>{{ customer.name }}</strong></p>

            <p class="card-text"> Age : <strong>{{ customer.age }}</strong></p>

            <p class="card-text"> Nombre de bières achetées : <strong>{{ customer.numberBeer }}</strong></p>
        </div>
        {% for stat in customer.statistics %}
        
            <p class="card-text"> Nom : <strong>{{ stat.beer.name }}</strong></p>
            <p class="card-text"> Score : <strong>{{ stat.score }}</strong></p>
        {% endfor %}
    </div> 
        
    {% endfor %}


{% endblock %}