src/Entity/Beer.php
<?php

namespace App\Entity;

use App\Repository\BeerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BeerRepository::class)
 */
class Beer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity=Country::class, inversedBy="beers")
     */
    private $country_id;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $published_at;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, mappedBy="beer")
     */
    private $categories;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $degree;

    /**
     * @ORM\OneToMany(targetEntity=Statistic::class, mappedBy="beer")
     */
    private $statistics;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->statistics = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCountryId(): ?Country
    {
        return $this->country_id;
    }

    public function setCountryId(?Country $country_id): self
    {
        $this->country_id = $country_id;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->published_at;
    }

    public function setPublishedAt(?\DateTimeInterface $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addBeer($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->removeElement($category)) {
            $category->removeBeer($this);
        }

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDegree(): ?int
    {
        return $this->degree;
    }

    public function setDegree(?int $degree): self
    {
        $this->degree = $degree;

        return $this;
    }

    /**
     * @return Collection|Statistic[]
     */
    public function getStatistics(): Collection
    {
        return $this->statistics;
    }

    public function addStatistic(Statistic $statistic): self
    {
        if (!$this->statistics->contains($statistic)) {
            $this->statistics[] = $statistic;
            $statistic->setBeer($this);
        }

        return $this;
    }

    public function removeStatistic(Statistic $statistic): self
    {
        if ($this->statistics->removeElement($statistic)) {
            // set the owning side to null (unless already changed)
            if ($statistic->getBeer() === $this) {
                $statistic->setBeer(null);
            }
        }

        return $this;
    }
}

templates/beers/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
<div class="row">
{% for beer in beers %}
  <div class="col-sm-6">
    <div class="card card__beers">
      <div class="card-body">
        <h5 class="card-title">{{ beer.name }}</h5>
        <img src="{{ asset('assets/images/images.jpeg') }}" />
        {# <p>Price : {{ beer.price ?? 'aucune information' }} </p> #}
        <p>Degree : {{ beer.degree }} </p>
        {# <p>{{ beer.description }}</p> #}
        {# <p><small>Date d'invention : {{ beer.publishedAt | date('d/m/Y h:i:s') }} </small></p> #}
        {# <img src="{{ asset('build/images/beer_00.jpg') }}" /> #}
        {# Affichez les catégories dans lesquelles se trouvent vos bières  #}
        {# {% if beer.country  %}
            <p> Country : {{ beer.country.name}} </p>
        {% else %}
            <p>No country</p>
        {% endif %} #}
      </div>
    </div>
  </div>
{% endfor %}
</div>
{% endblock %}

templates/beers/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BarController!{% endblock %}

{% block body %}
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ beer.name }}</h5>
        <p class="card-text">{{ beer.description }}</p>
        <p class="card-text">Prix : <strong>{{ beer.price / 10 }} €</strong></p>
        <p class="card-text">Degrés : <strong>{{ beer.degree / 10 }}</strong></p>
        <p class="card-text">Provenance : <strong>{{ beer.countryId.name }}</strong></p>
        {% for category in beer.categories %}
          <p>Catégorie : <strong>{{ category.name }}</strong></p>
          <p>Term : <strong>{{ category.term }}</strong></p>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}